#!/usr/bin/env ruby

module Manager
  module Commands
    def help
      # TODO
    end
    
    def list
      # TODO
    end
    
    def check
      # TODO
    end
    
    def install(list)
      # TODO
    end
    
    def uninstall(list)
      # TODO
    end
  end
  
  class Session
    COMMANDS = %w(help list install uninstall check)
    
    def initialize(args)
      @args = args
    end
    
    def run
      command = @args.shift || 'help'
    end
  end
end

session = Manager::Session.new(ARGV.dup)
session.run