#!/usr/bin/env ruby

require 'rubygems'
require 'redis'

config = ARGV.any? { |a| a =~ /config/ }
if config
  puts "graph_title Redis Connections"
  puts "graph_category redis"
  puts "connections.label Active Connections"
else
  redis = Redis.new
  info  = redis.info
  puts "connections.value" + " " + (info['connected_clients'].to_i - 1).to_s
end

