#!/usr/bin/env ruby

require 'rubygems'
require 'redis'

config = ARGV.any? { |a| a =~ /config/ }
if config
  puts "graph_title Redis Changes since last save"
  puts "graph_category redis"
  puts "graph_args -l 0"
  puts "changes.label changes"
else
  redis = Redis.new
  info  = redis.info  
  puts "changes.value" + " " + info['changes_since_last_save'].to_s
end

