#!/usr/bin/env ruby

require 'rubygems'
require 'redis'

config = ARGV.any? { |a| a =~ /config/ }
if config
  puts "graph_title Redis Total Commands"
  puts "graph_category redis"
  puts "graph_args -l 0"
  puts "commands.label commands"
else
  redis = Redis.new
  info  = redis.info
  puts "commands.value" + " " + info['total_commands_processed'].to_s
end

