#!/usr/bin/env ruby

require 'rubygems'
require 'redis'

config = ARGV.any? { |a| a =~ /config/ }
if config
  puts "graph_title Redis Total Connections"
  puts "graph_category redis"
  puts "connections_received.label connections"
else
  redis = Redis.new
  info  = redis.info
  puts "connections_received.value" + " " + info['total_connections_received'].to_s
end

