#!/usr/bin/env ruby

require 'rubygems'
require 'redis'

config = ARGV.any? { |a| a =~ /config/ }
if config
  puts "graph_title Redis Memory"
  puts "graph_category redis"
  puts "graph_args --base 1024 -l 0"
  puts "memory.label memory"
else
  redis = Redis.new
  info  = redis.info
  puts "memory.value" + " " + info['used_memory'].to_s
end

